version: "3.7"
services:
  api_service:
    image: mirkitobtw/docker-app
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/docker_app?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=docker_app
networks:
  springapimysql-net:
